.\" Process this file with
.\" groff -man -Tlatin1 metamorphose.1
.\"

.TH METAMORPHOSE 1

.SH NAME
Métamorphose \- Métamorphose is a mass renaming program for files and folders.

.SH SYNOPSIS 
.B metamorphose [DIRECTORY]

.SH DESCRIPTION
A mass file and folder renaming program that combines great flexibility with an intuitive interface.
Allows many different renaming operations in a single utility, perfect for those that need to rename large numbers of files
and/or folders on a regular basis. However, the ease of the interface ensures a one-time user will not find it too
frustrating to use. 

.SH OPTIONS 
Only a target directory can be used as an option. The GUI will open this directory, otherwise it defaults to no directory
and the user must navigate to the desired one.

.SH FILES
/home/USERNAME/.metamorphose

.SH RESOURCES 
Python 2.4 or 2.5, wxPython 2.6

.SH "SEE ALSO"
.BR python(1)

.SH COPYRIGHT 
Métamorphose is Copyright (c) 2005-2007 Ianaré Sévi.

This program is free software; you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published 
by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
GNU General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software 
Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
MA 02111-1307 USA.

.SH BUGS 
Please check the bug reports at the project page:
.P
.B http://sourceforge.net/projects/file-folder-ren

.SH AUTHOR
Ianaré Sévi (ianare@gmail.com)
